# Generated by Django 5.1.5 on 2025-01-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses/additional_images/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='houses.house')),
            ],
        ),
    ]
