# Generated by Django 5.1.5 on 2025-01-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_rename_contacts_complaint_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
