# Generated by Django 5.1.5 on 2025-01-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_remove_payment_is_approved_alter_invoice_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_no', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=15)),
                ('receipt', models.ImageField(upload_to='receipts/')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment\xa0Records',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
