# Generated by Django 5.1.5 on 2025-01-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_no',
            field=models.CharField(default='Not Provided', max_length=10),
        ),
    ]
