# Generated by Django 5.1.5 on 2025-01-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_alter_paymentrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='name',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
