# Generated by Django 5.1.5 on 2025-01-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_house_name_house_rating_house_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='house',
            name='review',
        ),
    ]
